name: "conditional workflow example"

on:
  push

jobs:
  Hello-world
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello world!"
  
  Goodbye-Sumanth
    runs-on: ubuntu-latest
    steps:
      - name: "goodbye"
        run: echo "Goodbye Sumanth!"