name: "context examples"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      my_value: "Hello"
    steps:
      - name: env info 
        run: |
          echo "Action: ${{ github.action }}"
      
      - name: actor info
        run: |
          echo "Actor: ${{ github.actor }}"
      
      - name: print env
        run: |
          echo "environment variable info ${{ env.my_value }}"

      #- name: print info about step env info
      # output: ${{ steps.env info.outputs }}

