name: workflow to display time on schedule time

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  hello-world:
    runs-on: ubuntu-latest                  #runs-on specifies the environment (or runner) where the jobs in a workflow will be executed.
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
